stages:   
  - build
  - test
  - deploy

image: python:alpine

build site:
  stage: build
  script:
  - pip install mkdocs mkdocs-material pymdown-extensions
  - mkdocs build
  - mv site public
  artifacts:     
    expire_in: 1 day
    paths:
    - public

test site:
  stage: test
  script:
    - echo fake result as a placeholder

deploy dev:
# Test bump to triffer CI
#  image: garland/docker-s3cmd
  image: alpine
  stage: deploy
  environment: development
  except:
  - master
  script:
    - apk add rsync openssh --no-cache
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - mkdir .ssh
    - chmod 700 .ssh
    - echo -e $SSHKEY | sed 's/^ //' > .ssh/id_ed25519 
    - chmod 600 .ssh/id_ed25519
    - rsync -avr --delete -e 'ssh -i .ssh/id_ed25519' public $SSHUSER@$SSHHOST:$SSHPATH/geeks-cookbook-dev
#    - export LC_ALL=C.UTF-8
#    - export LANG=C.UTF-8
#    - s3cmd --no-mime-magic --access_key=$ACCESS_KEY --secret_key=$SECRET_KEY --acl-public --delete-removed --delete-after --no-ssl --host=$S3HOST --host-bucket='$S3HOSTBUCKET' sync public s3://geeks-cookbook-dev

deploy prod:
  image: alpine
  stage: deploy
  environment: production
  except:
  - master
  script:
    - apk add rsync openssh --no-cache
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - mkdir .ssh
    - chmod 700 .ssh
    - echo -e $SSHKEY | sed 's/^ //' > .ssh/id_ed25519 
    - chmod 600 .ssh/id_ed25519
    - rsync -avr --delete -e 'ssh -i .ssh/id_ed25519' public $SSHUSER@$SSHHOST:$SSHPATH/geeks-cookbook
