lang: python
branches:
  except:
  - leanpub-preview
  - leanpub-publish
script:
- scripts/markdown-to-markua.sh
after_success:
- scripts/push-markua-to-branch.sh
env:
  secure: X0ruiXtzArHPaOAd5cQS0axHGwMM5HwqSHASr/KnzV1yZUPzJIrzJQYSCJmFPzk6zuboA2Tsa96zu+DftgA9N9WgzTYmjp8M10y9vcK4cpkfi5frs7GVorVLPQ5kcWwYPf/j+YzpP5OwrRSxDDG853GJ4OhoALcjmmBJk8NwIKZOkA6x2RvvcDRx6dc216QdhmouD5Hz0tImkE2rYdQNm44IN7OF6wekbEhOzN2Chz6yGit3duRvxBrNOPqmGqkFwtg0sxyQO0iBa4qvg88qrKQOIHwUG5y4rp8QcdqfRMv/lSNGEg1Mh7iDUHbZpvcAoXREXp9FMEY/SJ1uYkcEMn+GvLDQ/BOFwKjC/duWM3oMPgzjqI+gwpIdlTZt5+Qu9v4Z6+XJ5P+JIWZYtzudDVuOzVMSIzwk9y2a/ufYXGQdvGktf6H51WCcA8CO2muxLtDwDtV1okAVm+HXkgQ/pcwjqqq3n3RojN6Xxm+TJggn3HgU21qug/K1lukycwCjQbI8s0ey3soT1+oPc8Fl95n35eXTUY3DOd0u14e0Y3XKIbG9Rvyp9U8gJC2Ij6+EXSdHlFhvr5tJJLNwXkXjV3yMnLgtlSnuGBGHUpv0+XZuSsGqOropl/KDUurb2TGkIH7PjpBpFm6PhSbLViGXrupuxTvKLdsXBXospzODuEQ=
  global:
    secure: VRvMlfLCPYa7/E8zE6RBNRIcKCxaIeVMkcvt33TgBLlDUhskDaWxRE9AboFfw4lSRpvuzOUWMpytSQ1VOlL6RIQgceyLgdZFp8iOcuthJs/UuKODAQbmY0uW4RfAX3KQehaz95vfstLZdvglQR1tdYAucYCfZVxTbUDNotnZjYZGjGdAZCf3ZymeZgTjUDQakiIY6iE0TXG8aBVltW38FbZu9jifKTe9rg1IiDGti12ehJDfKeBPdUloDzdSSOkqXTcBWmyYoTKvtS6EKQVTbJk4Wj/QssGwtYBAYnWup1AI2uxlT4R8Kh5jHjaIM8s+55LX6vU4VrIexeGrNsef9SJZVnMWGrq+2vpLyoN4EzxT3K3S6R4mnUG+JslmEtu78YNCfA6N6xgVLWNfKHZjdoeuJs4KPsTWpHCyArkjfBbV3cQKvGsNgG80ozXKv9stLqdM+HfNlCWYhsVrKwKVu+1zlc1Nl8DL67wGKrcUxMj3ayBDXhbUfB2ed0IhbQdKZLkMZtRrxytrAVbHtVuOYckQlhTO9WjRvBI+F9EI8i8DDN71023BKbEEi7tKDDgTdlJ2puIMqrnt+6DJ7xJAL235jKcXquL2TWyAsLsNk1Djkr6jGkJ2kwZbFNQucBp3s0MGY2SvEWFI4rWY80MvPT+2PBuICyfS0BAeI2forzA=
