site_name: Funky Penguin's Geek Cookbook
site_description: 'The "Geek Cookbook" is a collection of guides for establishing your own highly-available docker container cluster (swarm). This swarm enables you to run self-hosted services such as GitLab, Plex, NextCloud, etc.'
site_author: 'David Young'
site_url: 'https://geek-cookbook.funkypenguin.co.nz'
edit_uri: 'edit/master/manuscript/'

# Fail to build if we have broken links
strict: true

# Repository
repo_name: 'funkypenguin/geek-cookbook'
repo_url: 'https://github.com/funkypenguin/geek-cookbook'

# Set this to "manuscript" so that we can produce leanpub content
docs_dir: 'manuscript'

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 David Young'


#theme_dir: mkdocs-material
pages:
    - Home : index.md
    - Introduction:
      - README: README.md
      - CHANGELOG: CHANGELOG.md
      - whoami: whoami.md
    - Essential:
      - Design: ha-docker-swarm/design.md
      - VMs: ha-docker-swarm/vms.md
      - Shared Storage (Ceph): ha-docker-swarm/shared-storage-ceph.md
      - Shared Storage (GlusterFS): ha-docker-swarm/shared-storage-gluster.md
      - Keepalived: ha-docker-swarm/keepalived.md
      - Traefik: ha-docker-swarm/traefik.md
      - Docker Swarm Mode: ha-docker-swarm/docker-swarm-mode.md
      - Mail Server: recipies/mail.md
      - Duplicity: recipies/duplicity.md
    - Chef's Favorites:
      - Huginn: recipies/huginn.md
      - Kanboard: recipies/kanboard.md
      - Miniflux: recipies/miniflux.md
      - Gollum: recipies/gollum.md
      - AutoPirate: recipies/autopirate.md
      - NextCloud: recipies/nextcloud.md
      - Plex: recipies/plex.md
      - Emby: recipies/emby.md
      - Home Assistant: recipies/homeassistant.md
    - Menu:
      - Ghost: recipies/ghost.md
      - GitLab: recipies/gitlab.md
      - GitLab Runner: recipies/gitlab-runner.md
      - Piwik: recipies/piwik.md
      - Wekan: recipies/wekan.md
      - Tiny Tiny RSS: recipies/tiny-tiny-rss.md
      - Portainer: recipies/portainer.md
    - Reference:
      - OAuth Proxy: reference/oauth_proxy.md
      - Data Layout: reference/data_layout.md
      - Networks: reference/networks.md
      - git-docker : reference/git-docker.md
      - OpenVPN : reference/openvpn.md
    - Support: support.md

theme:
  name: 'material'
  custom_dir: 'overrides'
  disqus: 'geeks-cookbook'
  logo: 'images/site-logo.png'
  favicon: 'images/favicon.ico'
  feature:
    tabs: false
  palette:
    primary: 'brown'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/funkypenguin'
    - type: 'twitter'
      link: 'https://twitter.com/funkypenguin'
    - type: 'stack-overflow'
      link: 'https://stackoverflow.com/cv/funkypenguin'
    - type: 'rss'
      link: 'https://www.funkypenguin.co.nz/blog/'
    - type: 'envelope'
      link: 'mailto:davidy@funkypenguin.co.nz?Subject=Hello%2C%20from%20a%20geek-cookbook%20reader%20%3B%29'
    - type: 'book'
      link: 'https://leanpub.com/geeks-cookbook'

# Google Analytics
google_analytics:
  - 'UA-139253-18'
  - 'auto'

extra_javascript:
  - 'extras/javascript/piwik.js'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - meta
